### ISSUE TITLE
backward algorithm

### ISSUE THREAD

**Issue by s33k3rs** [ahmedfgad/NumPyANN#1]
I get this error "IndexError: tuple index out of range" ?

and 

how about implementing this method with backward algorithm?

**Comment by ahmedfgad** [comment]
Could you please mention whether you made any changes to the project? If YES, then please post the modified code.
If not modifications made, please let me know the exact part of the code that returns this error.
This project uses genetic algorithm (GA) for updating the neural network weights. You can calculate the gradients in the backward pass for updating the wights rather than using GA.
Let me know if something is not clear.

**Comment by s33k3rs** [comment]
![error](https://user-images.githubusercontent.com/11786565/54148660-2c79a280-4467-11e9-87bc-0218030c6c37.jpg)

I just clone and try running in python 2.7 and python 3.6, but the same result

**Comment by oguzzkck** [comment]
we try running in python 3.7 but same result

**Comment by ahmedfgad** [comment]
I solved the issue and everything is working correctly now.
The problem is that the features array is not passed correctly to the dump() function correctly. The previous line pickle.dump("dataset_features.pkl", f), where the array name was mistakenly written as a string file name with its extension, is replaced by pickle.dump(dataset_features, f) where the array name dataset_features is passed correctly.
