### ISSUE TITLE
Doubt at line 28

### ISSUE THREAD

**Issue by p-suresh-kumar** [ahmedfgad/NumPyANN#5]
Why this line written "curr_weights = weights[-1]" 

if we are having more number of hidden layers then it will take the last index of weighted matrix instead of taking weights[1]

**Comment by ahmedfgad** [comment]
This line fetches the weights of the output layer which are added into the last element in the `weights` array. Thus, we use the index `-1`.

**Comment by p-suresh-kumar** [comment]
Here Network architecture is 3 layer so shape of the weights are 3

at first when finding r1 it will take weights[0], and then next it will take weights[-1] (which means weights[2] instead of weights[1]).

Once check

**Comment by ahmedfgad** [comment]
If there are 3 hidden layers followed by an output layer, then the length of the `weights` array is `(3+1)=4`.

The inner `for` loop inside the `train_network()` function starts from 0 and stops at the length of the `weights` array `subtracted by 1`. That is it stops at `4-1=3`. When the stop of the `for` loop is `3`, then the possible values for the `idx` variable of that loop are `0`, `1`, and `2` for a total of `3 iterations`. Each iteration of the loop works for a hidden layer. What about the output layer? 

Calculations of the output layer come outside the inner loop. Because the weights of that layer are at the end of the `weights` array, then it is indexed using the index `-1`.
